name: ulearning_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_screenutil: ^5.9.3
  dots_indicator: ^3.0.0
  intl: ^0.20.2
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.2
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/voice/
    - .env